cameras:
- camera_id: cam_nave3_hornos_a_cam3
  forbidden_rois:
  - name: cam_nave3_hornos_a_cam3
    points:
    - - 498
      - 878
    - - 597
      - 453
    - - 955
      - 397
    - - 968
      - 823
  allowed_classes:
  - pine
  - worker
  alert_classes:
  - object
  strict_mode: true
- camera_id: cam_nave3_hornos_a
  forbidden_rois:
  - name: cam_nave3_hornos_a
    points:
    - - 392
      - 1339
    - - 593
      - 877
    - - 2346
      - 1086
    - - 2400
      - 1509
  allowed_classes:
  - pine
  - worker
  alert_classes:
  - object
  strict_mode: true
- camera_id: cam_nave3_hornos_b
  forbidden_rois:
  - name: cam_nave3_hornos_b
    points:
    - - 350
      - 1420
    - - 538
      - 1053
    - - 2161
      - 1058
    - - 2199
      - 1431
  allowed_classes:
  - pine
  - worker
  alert_classes:
  - object
  strict_mode: true
- camera_id: cam_nave3_hornos_b_cam3
  forbidden_rois:
  - name: cam_nave3_hornosb_cam3_1
    points:
    - - 1419
      - 1135
    - - 933
      - 1204
    - - 861
      - 817
    - - 1203
      - 779
  - name: cam_nave3_hornos_b_cam3_2
    points:
    - - 441
      - 1429
    - - 484
      - 834
    - - 855
      - 807
    - - 980
      - 1422
  allowed_classes:
  - pine
  - worker
  alert_classes:
  - object
  strict_mode: true
- camera_id: cam_nave4_difusor_a
  forbidden_rois:
  - name: cam_nave4_difusor_a
    points:
    - - 230
      - 1499
    - - 447
      - 884
    - - 2041
      - 950
    - - 2290
      - 1484
  allowed_classes:
  - pine
  - worker
  alert_classes:
  - object
  strict_mode: true
- camera_id: cam_nave4_difusor_a_cam3
  forbidden_rois:
  - name: cam_nave4_difusor_a_cam3
    points:
    - - 153
      - 1329
    - - 393
      - 170
    - - 2092
      - 305
    - - 1982
      - 1424
  allowed_classes:
  - pine
  - worker
  alert_classes:
  - object
  strict_mode: true
- camera_id: cam_nave4_difusor_b
  forbidden_rois:
  - name: cam_nave4_difusor_b
    points:
    - - 342
      - 1419
    - - 551
      - 876
    - - 2088
      - 742
    - - 2337
      - 1430
  allowed_classes:
  - pine
  - worker
  alert_classes:
  - object
  strict_mode: true
- camera_id: cam_nave4_difusor_b_cam3
  forbidden_rois:
  - name: cam_nave4_difusor_cam3
    points:
    - - 722
      - 1381
    - - 901
      - 6
    - - 2444
      - 2
    - - 2513
      - 1424
  allowed_classes:
  - pine
  - worker
  alert_classes:
  - object
  strict_mode: true
